version: '3.8'

services:
  faktory:
    image: contribsys/faktory:latest
    ports:
      - "7419:7419"
      - "7420:7420"
    stdin_open: true
    tty: true
    command: /faktory -b :7419 -w :7420
    networks:
      - keepup

  keepup:
    build:
      context: .
      dockerfile: docker/Dockerfile
      target: dev
    depends_on:
      - faktory
    stdin_open: true
    tty: true
    networks:
      - keepup

networks:
  keepup:
    name: keepup
